/**
 * Fit valuation centres from on-disk history into data/val-center.json.
 * Live meaning.js reads snap.valCenter (patched here); hardcoded defaults
 * remain as fallback. HY keeps the band mid — FRED’s ICE print is ~3y of tights.
 *
 *   npm run calibrate:val
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const HIST = path.join(ROOT, "data", "history");
const OUT = path.join(ROOT, "data", "val-center.json");
const SINCE = "2003-01-01";

/** Scales stay in economic units (how much move is a full z). Medians come from the archive. */
const SPECS = [
  { id: "THREEFFTP10", scale: 0.75 },
  { id: "DFII10", scale: 0.8 },
  {
    id: "BAMLH0A0HYM2",
    scale: 1.5,
    median: 4.0,
    source: "band-mid",
    why: "ICE HY OAS on FRED is ~3y of cycle tights; the centre is the long-run typical (band mid), not this download.",
  },
  { id: "BAA10Y", scale: 0.7 },
  { id: "EQUITY_ERP", scale: 1.5 },
  { id: "SPX_EY", scale: 1.0 },
];

function median(vals) {
  if (!vals.length) return null;
  const s = [...vals].sort((a, b) => a - b);
  const m = Math.floor(s.length / 2);
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
}

async function loadPoints(id) {
  try {
    const raw = JSON.parse(await fs.readFile(path.join(HIST, `${id}.json`), "utf8"));
    return (raw.points || [])
      .filter((p) => p?.date && p.date >= SINCE && Number.isFinite(p.value))
      .sort((a, b) => a.date.localeCompare(b.date));
  } catch {
    return [];
  }
}

async function patchSnapshot(centers) {
  for (const snapPath of [path.join(ROOT, "data", "snapshot.json"), path.join(ROOT, "snapshot.json")]) {
    try {
      const snap = JSON.parse(await fs.readFile(snapPath, "utf8"));
      snap.valCenter = centers;
      await fs.writeFile(snapPath, JSON.stringify(snap, null, 2) + "\n");
    } catch (e) {
      console.log(`  ! could not patch ${path.relative(ROOT, snapPath)}: ${e.message}`);
    }
  }
}

async function loadCommitted() {
  try {
    return JSON.parse(await fs.readFile(OUT, "utf8"));
  } catch {
    return null;
  }
}

async function main() {
  const centers = {};
  let sampleFrom = null;
  let sampleTo = null;
  const missing = [];
  for (const spec of SPECS) {
    const pts = await loadPoints(spec.id);
    const vals = pts.map((p) => p.value);
    if (pts.length) {
      sampleFrom = sampleFrom && sampleFrom < pts[0].date ? sampleFrom : pts[0].date;
      const last = pts[pts.length - 1].date;
      sampleTo = sampleTo && sampleTo > last ? sampleTo : last;
    }
    const fromArchive = median(vals);
    const pinned = spec.source === "band-mid";
    const med = pinned ? spec.median : fromArchive;
    if (med == null || !Number.isFinite(med)) missing.push(spec.id);
  }
  if (missing.length) {
    const committed = await loadCommitted();
    if (committed?.centers) {
      console.log(
        `calibrate:val: keep committed val-center (no median for ${missing.join(", ")})`
      );
      await patchSnapshot(committed.centers);
      return;
    }
    console.error(`calibrate:val: no median for ${missing.join(", ")}`);
    process.exit(1);
  }
  for (const spec of SPECS) {
    const pts = await loadPoints(spec.id);
    const vals = pts.map((p) => p.value);
    const fromArchive = median(vals);
    const pinned = spec.source === "band-mid";
    const med = pinned ? spec.median : fromArchive;
    centers[spec.id] = {
      median: Number(med.toFixed(4)),
      scale: spec.scale,
      n: vals.length,
      source: spec.source || "archive-median",
      archiveMedian: fromArchive != null ? Number(fromArchive.toFixed(4)) : null,
      sampleFrom: pts[0]?.date || null,
      sampleTo: pts[pts.length - 1]?.date || null,
      ...(spec.why ? { why: spec.why } : {}),
    };
  }

  const out = {
    version: 1,
    fittedAt: new Date().toISOString(),
    sampleFrom,
    sampleTo,
    note:
      "Valuation centres from the 2003+ archive. HY is the band mid, not the short ICE download. Regenerated by npm run calibrate:val.",
    centers,
  };
  await fs.writeFile(OUT, JSON.stringify(out, null, 2) + "\n");
  await patchSnapshot(centers);

  console.log(`val-center → ${path.relative(ROOT, OUT)}`);
  console.log(`  sample ${sampleFrom} → ${sampleTo}`);
  for (const spec of SPECS) {
    const c = centers[spec.id];
    const flag = c.source === "band-mid" ? `  (band mid; archive ${c.archiveMedian})` : "";
    console.log(
      `  ${spec.id.padEnd(16)} median ${c.median.toFixed(4)}  scale ${c.scale}  n=${c.n}${flag}`
    );
  }
}

main().catch((e) => {
  console.error(`calibrate:val failed: ${e.message}`);
  process.exit(1);
});
