/**
 * Fit full-sample light centres from regime-history raw composites and write
 * data/light-dist.json. Live display reads that file; bake:history uses an
 * expanding window so the archive never sees its own future.
 *
 *   npm run calibrate:lights
 *
 * Prefers row.raw written by bake:history. If the archive has no raw column
 * yet, refuses rather than refitting calibrated scores onto themselves
 * (that would print mean 0 / sd REF — the in-sample trap).
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { LIGHT_IDS, fitLightDist, setLightDist, buildLights, attachImpulse, DEFAULT_IMPULSE } from "../score.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const HIST = path.join(ROOT, "data", "regime-history.json");
const OUT = path.join(ROOT, "data", "light-dist.json");

async function main() {
  let hist;
  try {
    hist = JSON.parse(await fs.readFile(HIST, "utf8"));
  } catch {
    console.error("calibrate:lights needs data/regime-history.json — run npm run bake:history");
    process.exit(1);
  }
  const rows = hist.rows || [];
  const withRaw = rows.filter((r) => Array.isArray(r.raw) && r.raw.length === LIGHT_IDS.length);
  if (withRaw.length < 252) {
    console.error(
      `calibrate:lights needs row.raw on the archive (${withRaw.length} days have it). ` +
        `Re-run npm run bake:history so each day stores the pre-threshold composite.`
    );
    process.exit(1);
  }

  const rawByLight = Object.fromEntries(LIGHT_IDS.map((id) => [id, []]));
  for (const r of withRaw) {
    LIGHT_IDS.forEach((id, i) => {
      if (Number.isFinite(r.raw[i])) rawByLight[id].push(r.raw[i]);
    });
  }

  const dist = fitLightDist(rawByLight, {
    sampleFrom: withRaw[0].date,
    sampleTo: withRaw[withRaw.length - 1].date,
    note:
      "Full-sample raw composite centres for live display. Regenerated by npm run calibrate:lights. " +
      "bake:history uses an expanding window so the archive has no look-ahead.",
  });
  setLightDist(dist);
  await fs.writeFile(OUT, JSON.stringify(dist, null, 2) + "\n");

  // Keep embedded snapshot centres in sync — ingest ran before this step.
  for (const snapPath of [
    path.join(ROOT, "data", "snapshot.json"),
    path.join(ROOT, "snapshot.json"),
  ]) {
    try {
      const snap = JSON.parse(await fs.readFile(snapPath, "utf8"));
      snap.lightDist = dist;
      const lights = buildLights(snap);
      attachImpulse(lights, snap, DEFAULT_IMPULSE);
      for (const id of LIGHT_IDS) {
        if (!snap.lights?.[id] || !lights[id]) continue;
        snap.lights[id].score = lights[id].score;
        snap.lights[id].state = lights[id].state;
        const w = lights[id].words;
        if (w && lights[id].state && w[lights[id].state]) {
          snap.lights[id].word = w[lights[id].state];
        }
      }
      await fs.writeFile(snapPath, JSON.stringify(snap, null, 2) + "\n");
    } catch (e) {
      console.log(`  ! could not patch ${path.relative(ROOT, snapPath)}: ${e.message}`);
    }
  }

  console.log(`light-dist → ${path.relative(ROOT, OUT)}`);
  console.log(`  sample ${dist.sampleFrom} → ${dist.sampleTo}  n=${dist.n}  refSd=${dist.refSd}`);
  for (const id of LIGHT_IDS) {
    const d = dist.lights[id];
    console.log(`  ${id.padEnd(10)} mean ${d.mean.toFixed(4)}  sd ${d.sd.toFixed(4)}`);
  }
}

main().catch((e) => {
  console.error(`calibrate:lights failed: ${e.message}`);
  process.exit(1);
});
